{
 "title": "Zyxel Access Point",
 "tags": [
  "zyxel",
  "wifi",
  "access-point",
  "network"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Access Point",
    "query": {
     "query": "label_values(access_point_device_security_type,instance)"
    }
   },
   {
    "name": "band",
    "label": "Band",
    "query": {
     "query": "label_values(access_point_device_security_type{instance=~\"$instance\"},band)"
    }
   },
   {
    "name": "security",
    "label": "Security",
    "query": {
     "query": "label_values(access_point_device_security_type{instance=~\"$instance\", band=~\"$band\"},security)"
    }
   },
   {
    "name": "ssid",
    "label": "SSID",
    "query": {
     "query": "label_values(access_point_device_security_type{instance=~\"$instance\", band=~\"$band\", security=~\"$security\"},ssid)"
    }
   },
   {
    "name": "mac",
    "label": "Station MAC",
    "query": {
     "query": "label_values(access_point_device_security_type{instance=~\"$instance\", band=~\"$band\", ssid=~\"$ssid\", security=~\"$security\"},mac)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$band Connected Devices",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "repeat": "band",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ssid) (access_point_connected_devices_total{instance=~\"$instance\", band=~\"$band\", ssid=~\"$ssid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Devices by SSID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ssid) (access_point_connected_devices_total{instance=~\"$instance\", band=~\"$band\", ssid=~\"$ssid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connected Devices by Band and SSID",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(ssid, band) (access_point_connected_devices_total{instance=~\"$instance\", band=~\"$band\", ssid=~\"$ssid\"})",
     "legendFormat": "{{ssid}} {{band}}"
    },
    {
     "expr": "sum(access_point_connected_devices_total{instance=~\"$instance\", band=~\"$band\", ssid=~\"$ssid\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "access_point_device_security_type{instance=~\"$instance\", band=~\"$band\", ssid=~\"$ssid\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}